# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default='pat', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='2000-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='pat', max_length=30),
            preserve_default=False,
        ),
    ]
